name: 🔎 Check links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: CDN
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
          args: '--base . ./src/data/svgs.ts --cache --max-cache-age 3d . --include "https://svgl.app"'
