[package]
name = "cfonts"
version = "1.1.4"
edition = "2021"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>"]
license = "GPL-3.0-or-later"
description = "Sexy ANSI fonts for the console"
readme = "../README.md"
homepage = "https://github.com/dominikwilkowski/cfonts"
repository = "https://github.com/dominikwilkowski/cfonts"
documentation = "https://docs.rs/cfonts/"
keywords = ["fonts", "color", "console", "ascii", "ANSI"]
categories = ["command-line-interface", "command-line-utilities", "graphics"]
include = ["/fonts", "/src", "!.DS_Store", "/LICENSE"]

[dependencies]
exitcode = "1.1.2"
strum = "0.25"
strum_macros = "0.25"
enable-ansi-support = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
terminal_size = "0.3"
supports-color = "2"

[dev-dependencies]
temp-env = "0.3.6"
assert_cmd = "2.0.13"
